namespace LearningLanguageBot.Infrastructure.Database.Models;

public class Card
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public long UserId { get; set; }
    public string Front { get; set; } = string.Empty;
    public string Back { get; set; } = string.Empty;
    public List<Example> Examples { get; set; } = [];
    public string SourceLang { get; set; } = string.Empty;
    public string TargetLang { get; set; } = string.Empty;

    // FSRS parameters
    public double Stability { get; set; }
    public double Difficulty { get; set; } = 0.3;
    public int State { get; set; }          // New=0, Learning=1, Review=2, Relearning=3
    public int Lapses { get; set; }
    public int Reps { get; set; }
    public DateTime? LastReview { get; set; }
    public DateTime NextReviewAt { get; set; } = DateTime.UtcNow;
    public bool IsLearned { get; set; }     // Для статистики (Stability >= 21 дней)

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Cached memory hint (etymology, usage, associations) generated by LLM.
    /// </summary>
    public string? MemoryHint { get; set; }

    public User User { get; set; } = null!;
    public ICollection<ReviewLog> ReviewLogs { get; set; } = new List<ReviewLog>();
}

public class Example
{
    public string Original { get; set; } = string.Empty;
    public string Translated { get; set; } = string.Empty;
}